name: catchafire
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.12.1
  geolocator: ^13.0.4
  
  smooth_page_indicator: ^1.2.1

  http: ^1.3.0

  image_picker: ^1.1.2

  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5

  shared_preferences: ^2.5.3

  cupertino_icons: ^1.0.8

  googleapis: ^14.0.0

  url_launcher: ^6.3.1

  path: ^1.8.2

  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/logo.png
    - assets/onboarding1.png
    - assets/onboarding2.png
    - assets/onboarding3.png
    - assets/onboarding4.png


  fonts:
    - family: GT Ultra
      fonts:
        - asset: assets/fonts/GTUltra-Black.otf
