// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0Ak8g4o4RBPa8qpCSDmKFrma35820BLc',
    appId: '1:306133157985:web:ba58d979655513bd154220',
    messagingSenderId: '306133157985',
    projectId: 'catchafire-74466',
    authDomain: 'catchafire-74466.firebaseapp.com',
    storageBucket: 'catchafire-74466.firebasestorage.app',
    measurementId: 'G-03SZ9ZRRRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmZ7LXLrxN1HeK984AUpDsCyptr4_ZHdM',
    appId: '1:306133157985:android:d7724cd867785d06154220',
    messagingSenderId: '306133157985',
    projectId: 'catchafire-74466',
    storageBucket: 'catchafire-74466.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL7mGwHGkWbGLNNSiMeynqAXOO8JKLSf8',
    appId: '1:306133157985:ios:ee535e530074ffa5154220',
    messagingSenderId: '306133157985',
    projectId: 'catchafire-74466',
    storageBucket: 'catchafire-74466.firebasestorage.app',
    iosBundleId: 'com.example.catchafire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL7mGwHGkWbGLNNSiMeynqAXOO8JKLSf8',
    appId: '1:306133157985:ios:ee535e530074ffa5154220',
    messagingSenderId: '306133157985',
    projectId: 'catchafire-74466',
    storageBucket: 'catchafire-74466.firebasestorage.app',
    iosBundleId: 'com.example.catchafire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0Ak8g4o4RBPa8qpCSDmKFrma35820BLc',
    appId: '1:306133157985:web:03632f7569f2598c154220',
    messagingSenderId: '306133157985',
    projectId: 'catchafire-74466',
    authDomain: 'catchafire-74466.firebaseapp.com',
    storageBucket: 'catchafire-74466.firebasestorage.app',
    measurementId: 'G-8YYHDDGXLZ',
  );
}
